---
# tasks file for dhcpd
- name: Installing dhcpd on CentOS
  dnf:
   name: dhcp-server.x86_64
   state: latest
   update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Installing dhcpd on Ubuntu
  apt:
   name: isc-dhcp-server
   state: latest
   update_cache: yes
  when: ansible_distribution == "Ubuntu"
